server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: DEMO-SERVICE
          uri: lb://DEMO-SERVICE
          predicates:
            - Path=/demo/**
        - id: SPRING-SERVICE
          uri: lb://SPRING-SERVICE
          predicates:
            - Path=/spring/**
        - id: DEMO
          uri: lb://DEMO
          predicates:
            - Path=/demoURL/**
        - id: SpringProject
          uri: lb://SpringProject
          predicates:
            - Path=/SpringProject/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost